# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/lenovo/TB125FU/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),TB125FU)
$(call add-radio-file-sha1-checked,radio/gz.img,9deadb6462be626db314986821a051c04f0391df)
$(call add-radio-file-sha1-checked,radio/lk.img,ae341a5d300e783f58f9b109ee360894c1d8629d)
$(call add-radio-file-sha1-checked,radio/md1img.img,6351b8f537823e0ce38a24094c0fdef6102c56a6)
$(call add-radio-file-sha1-checked,radio/preloader_raw.img,b217e0cf3b77126d1880ddf6a4688aacaa632fca)
$(call add-radio-file-sha1-checked,radio/scp.img,8817d3587c9aef1e4cb6cfa3d0d958c788dcf4d4)
$(call add-radio-file-sha1-checked,radio/spmfw.img,62d7a3ca1c33dab31ab3318c4b2774bcf2a119b4)
$(call add-radio-file-sha1-checked,radio/sspm.img,a9de89a19181f65d926ad6b0496137018070f382)
$(call add-radio-file-sha1-checked,radio/tee.img,0a4c6aadef27a57ba96ed8fb15cc276e90fe1ab2)
endif
